# Generated by Django 4.2.10 on 2024-03-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('available_location', models.CharField(max_length=20)),
                ('google_profile', models.URLField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('PG', 'Paying Guest (PG)'), ('Flat', 'Flat'), ('Independent', 'Independent'), ('Land', 'Land'), ('Building', 'Building')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('Rent', 'Rent'), ('Lease', 'Lease'), ('Sale', 'Sale')], max_length=20)),
                ('bhk', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=250)),
                ('picture1', models.ImageField(upload_to='assets/property_pictures')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='assets/property_pictures')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='assets/property_pictures')),
                ('description', models.TextField(max_length=1000)),
                ('price', models.PositiveIntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
